apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
  name: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      run: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
      app: DELIVERY_DOCUMENT
  template:
    metadata:
      labels:
        run: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
        app: DELIVERY_DOCUMENT
    spec:
      hostname: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
      containers:
        - name: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
          image: latonaio/convert-to-dpfm-delivery-document-from-sap-inbound-delivery
          imagePullPolicy: Always
          env:
            - name: "RMQ_QUEUE_FROM"
              value: "convert-to-dpfm-delivery-document-from-sap-inbound-delivery-queue"
            - name: "RMQ_QUEUE_TO"
              value: "convert-to-dpfm-delivery-document-from-sap-inbound-delivery-queue"
            - name: "RMQ_SESSION_CONTROL_QUEUE"
              value: "data-platform-api-delivery-document-creates-session-control-queue"
            - name: "DB_NAME"
              value: "DataPlatformMastersAndTransactionsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
  name: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
spec:
  selector:
    run: convert-to-dpfm-delivery-document-from-sap-inbound-delivery
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30906
